### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by VesnaT** [biolab/orange-web2#60]
- [x] Na prvi strani, pri features (pod blogom), naj bo vrstni red naslovov: 1.Visual Programming, 2. Interactive Data Visualization, 3. Add-ons Extend Functionality, 4. Orange Users.
- [X] Datumi pri blogih naj bodo v taki obliki: Nov 14, 2022
- [x] Gumb Search - mogoče ni potrebe, da je Search gumb tako dolg.
- [X] Na prvi strani gumb Download Orange 3.33.0 - napačna verzija, popravi na 3.36.1
- [X] Na prvi strani čisto na dnu Contribute to Orange manjka tekst namesto Lorem Ipsum.
- [x] Podstran Visual Programming https://neworange.biolab.si/home/visual-programming/ naj bo prvi naslov  Visual Programming levo poravnan. Isti popravek velja za podstrani Interactive Data  Visualization in Orange Users. Na podstrani Orange Users je treba popraviti hierarhijo velikosti naslovov.
- [x] Podstran Examples. Bodo tagi nad naslovom posamičnega primera tudi klikabilni?
- [x] Podstran Download. Pri naslovu Windows in macOS je body text zanalašč siv? Zakaj ni črn in tako velik, kot pri Other platforms?
- [x] Na prvi strani pri Orange Users je kvadrat v kateri so izjave uporabnikov različno osenčene od znotraj. Ne vem, meni je najbolj všeč, če kvadrat nima nobene sence znotraj, tako kot ima Francesca Vitali.
- [x] Podstran Blog. Kjer so trije blogi v vrsti. Razmik med naslovom bloga in opisom bloga naj bo 6px, torej enak, kot od naslova do vijoličnega taga.
- [ ] Podstran Blog. Mislim, da bi morale imeti slike nek tanek siv rob okoli.
- [ ] Podstran Workshops. Tukaj je bila mišljena neka druga ilustracija, da ne bo ista, kot na prvi strani. Če se strinjate, jo narišem.
- [x] Podstran Workshops. V zavihkih, kjer je opis tečaja. Ponekod je Included z dvopičjem, ponekod brez.
- [ ] Podstran Download. Kvadratek z Installing add-ons. Zadaj je sedaj začasna slika z baloni (reusana od drugod). Mišljeno je bilo, da jo malo prilagodim.
- [x] Podstran Download. Na vseh straneh Orange so vse besede v naslovih z veliko začetnico, na Download strani pa niso. Jaz bi poenotila, vse z veliko začetnico. Aha, tudi na prvi Orange strani je Data mining Fruitful and fun, nekaj z malo, nekaj z veliko začetnico. Jaz bi popravila na Data Mining Fruitful and Fun.
- [x] Migracija zadnjih blogov

**Comment by markotoplak** [comment]
Tole: Podstran Download. Pri naslovu Windows in macOS je body text zanalašč siv? Zakaj ni črn in tako velik, kot pri Other platforms?

Torej besedilo na Download strani je še vedno nekonsistentno (pri Win in Mac je siv in majhen).

**Comment by mitjapotocin** [comment]
Prehitro si testiral. Verjetno se ni bilo deployano.

**Comment by mitjapotocin** [comment]
Naredim sem, da so tagi klikabilni, ampak je kr cudn UX, ko ti blog zgine izpod miške.

https://github.com/biolab/orange-web2/assets/36345162/c36af188-a61b-4b3f-bb1a-d72fe7e3bf6f

**Comment by markotoplak** [comment]
@mitjapotocin, se strinjam. Morda tule ne, na posameznih postih pa tega problema ni.
